// @ts-check

import pluginEslintComments from "eslint-plugin-eslint-comments";
import pluginImport from "eslint-plugin-import";
import pluginPromise from "eslint-plugin-promise";
import pluginUnicorn from "eslint-plugin-unicorn";
import { allJsFiles } from "../utils.ts";
import tseslint from "typescript-eslint";
import js from "@eslint/js";

/** @type {import("typescript-eslint").ConfigArray} */
export default tseslint.config({
  files: allJsFiles,
  extends: [js.configs.recommended],
  plugins: {
    "eslint-comments": pluginEslintComments,
    import: pluginImport,
    promise: pluginPromise,
    unicorn: pluginUnicorn,
  },
  rules: {
    "eslint-comments/disable-enable-pair": [
      2,
      {
        allowWholeFile: true,
      },
    ],
    "eslint-comments/no-aggregating-enable": 2,
    "eslint-comments/no-duplicate-disable": 2,
    "eslint-comments/no-restricted-disable": 0,
    "eslint-comments/no-unlimited-disable": 2,
    "eslint-comments/no-unused-disable": 0,
    "eslint-comments/no-unused-enable": 0,
    "eslint-comments/no-use": 0,
    "eslint-comments/require-description": 0,
    "import/consistent-type-specifier-style": [2, "prefer-inline"],
    "import/default": 2,
    "import/dynamic-import-chunkname": 0,
    "import/export": 2,
    "import/exports-last": 0,
    "import/extensions": 0,
    "import/group-exports": 0,
    "import/max-dependencies": 0,
    "import/named": 0,
    "import/namespace": 0,
    "import/no-absolute-path": 2,
    "import/no-amd": 2,
    "import/no-anonymous-default-export": 0,
    "import/no-commonjs": 0,
    "import/no-cycle": 2,
    "import/no-default-export": 0,
    "import/no-deprecated": 1,
    "import/no-duplicates": [
      2,
      {
        considerQueryString: true,
        "prefer-inline": true,
      },
    ],
    "import/no-dynamic-require": 2,
    "import/no-extraneous-dependencies": [
      2,
      {
        devDependencies: true,
        optionalDependencies: true,
        peerDependencies: true,
      },
    ],
    "import/no-import-module-exports": 0,
    "import/no-internal-modules": 0,
    "import/no-mutable-exports": 2,
    "import/no-named-as-default": 2,
    "import/no-named-as-default-member": 2,
    "import/no-named-default": 2,
    "import/no-named-export": 0,
    "import/no-namespace": 0,
    "import/no-nodejs-modules": 0,
    "import/no-relative-packages": 0,
    "import/no-relative-parent-imports": 0,
    "import/no-restricted-paths": 0,
    "import/no-self-import": 2,
    "import/no-unassigned-import": 2,
    "import/no-unresolved": 0,
    "import/no-unused-modules": 0,
    "import/no-useless-path-segments": [
      2,
      {
        noUselessIndex: true,
      },
    ],
    "import/no-webpack-loader-syntax": 2,
    "import/prefer-default-export": 0,
    "import/unambiguous": 0,
    "init-declarations": 0,
    "max-classes-per-file": 0,
    "max-depth": 0,
    "max-lines": 0,
    "max-lines-per-function": 0,
    "max-nested-callbacks": 0,
    "max-params": 0,
    "max-statements": 0,
    "new-cap": 0,
    "no-alert": 2,
    "no-async-promise-executor": 2,
    "no-await-in-loop": 0,
    "no-bitwise": 2,
    "no-caller": 2,
    "no-console": 2,
    "no-constant-condition": 0,
    "no-constructor-return": 2,
    "no-continue": 0,
    "no-div-regex": 2,
    "no-duplicate-imports": 0,
    "no-else-return": 0,
    "no-eq-null": 2,
    "no-eval": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-extra-label": 2,
    "no-fallthrough": 0,
    "no-implicit-coercion": 2,
    "no-implicit-globals": 2,
    "no-implied-eval": 2,
    "no-inline-comments": 2,
    "no-invalid-this": 0,
    "no-iterator": 2,
    "no-label-var": 2,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-lonely-if": 2,
    "no-loop-func": 2,
    "no-magic-numbers": 0,
    "no-multi-assign": 2,
    "no-multi-str": 2,
    "no-negated-condition": 2,
    "no-nested-ternary": 0,
    "no-new": 2,
    "no-new-func": 2,
    "no-new-object": 2,
    "no-new-wrappers": 2,
    "no-param-reassign": [
      2,
      {
        props: false,
      },
    ],
    "no-plusplus": 0,
    "no-promise-executor-return": 2,
    "no-proto": 2,
    "no-redeclare": [
      2,
      {
        builtinGlobals: true,
      },
    ],
    "no-restricted-exports": 0,
    "no-restricted-globals": 0,
    "no-restricted-imports": 0,
    "no-restricted-properties": 0,
    "no-restricted-syntax": 0,
    "no-return-assign": 2,
    "no-script-url": 2,
    "no-self-compare": 2,
    "no-sequences": 2,
    "no-shadow": [
      2,
      {
        builtinGlobals: false,
        hoist: "all",
      },
    ],
    "no-ternary": 0,
    "no-throw-literal": 2,
    "no-undef-init": 2,
    "no-undefined": 0,
    "no-underscore-dangle": 0,
    "no-unmodified-loop-condition": 2,
    "no-unneeded-ternary": 2,
    "no-unreachable": 0,
    "no-unreachable-loop": 2,
    "no-unused-expressions": 2,
    "no-unused-private-class-members": 0,
    "no-use-before-define": [
      2,
      {
        classes: true,
        functions: false,
        variables: true,
      },
    ],
    "no-useless-call": 2,
    "no-useless-computed-key": 2,
    "no-useless-concat": 2,
    "no-useless-constructor": 2,
    "no-useless-rename": [
      2,
      {
        ignoreDestructuring: false,
        ignoreExport: false,
        ignoreImport: false,
      },
    ],
    "no-useless-return": 2,
    "no-var": 2,
    "no-void": [
      2,
      {
        allowAsStatement: true,
      },
    ],
    "no-warning-comments": [
      1,
      {
        location: "start",
        terms: ["todo", "@toto"],
      },
    ],
    "one-var": [2, "never"],
    "operator-assignment": [2, "always"],
    "prefer-arrow-callback": 2,
    "prefer-const": 2,
    "prefer-destructuring": 0,
    "prefer-exponentiation-operator": 2,
    "prefer-named-capture-group": 0,
    "prefer-numeric-literals": 2,
    "prefer-object-spread": 2,
    "prefer-promise-reject-errors": 2,
    "prefer-regex-literals": [
      2,
      {
        disallowRedundantWrapping: true,
      },
    ],
    "prefer-rest-params": 2,
    "prefer-spread": 2,
    "prefer-template": 0,
    "promise/param-names": 2,
    "promise/prefer-await-to-callbacks": 0,
    "promise/prefer-await-to-then": 2,
    "promise/valid-params": 2,
    radix: 2,
    "require-atomic-updates": 2,
    "require-await": 0,
    "require-unicode-regexp": 2,
    "require-yield": 2,
    "sort-vars": 2,
    strict: [2, "never"],
    "symbol-description": 2,
    "unicorn/better-regex": 2,
    "unicorn/catch-error-name": [
      "error",
      {
        name: "error",
      },
    ],
    "unicorn/consistent-destructuring": 0,
    "unicorn/consistent-function-scoping": 2,
    "unicorn/custom-error-definition": 0,
    "unicorn/error-message": 2,
    "unicorn/escape-case": 2,
    "unicorn/expiring-todo-comments": 0,
    "unicorn/explicit-length-check": 0,
    "unicorn/filename-case": 0,
    "unicorn/import-style": 0,
    "unicorn/new-for-builtins": 2,
    "unicorn/no-abusive-eslint-disable": 2,
    "unicorn/no-array-callback-reference": 0,
    "unicorn/no-array-for-each": 2,
    "unicorn/no-array-method-this-argument": 2,
    "unicorn/no-array-reduce": [
      "error",
      {
        allowSimpleOperations: true,
      },
    ],
    "unicorn/no-array-reverse": 2,
    "unicorn/no-await-expression-member": 0,
    "unicorn/no-console-spaces": 0,
    "unicorn/no-document-cookie": 2,
    "unicorn/no-empty-file": 2,
    "unicorn/no-for-loop": 2,
    "unicorn/no-hex-escape": 2,
    "unicorn/no-instanceof-array": 2,
    "unicorn/no-invalid-remove-event-listener": 2,
    "unicorn/no-keyword-prefix": 0,
    "unicorn/no-lonely-if": 2,
    "unicorn/no-nested-ternary": 2,
    "unicorn/no-new-array": 2,
    "unicorn/no-new-buffer": 2,
    "unicorn/no-null": 0,
    "unicorn/no-object-as-default-parameter": 2,
    "unicorn/no-process-exit": 0,
    "unicorn/no-static-only-class": 2,
    "unicorn/no-thenable": 2,
    "unicorn/no-this-assignment": 2,
    "unicorn/no-unnecessary-array-flat-depth": 2,
    "unicorn/no-unnecessary-array-splice-count": 2,
    "unicorn/no-unreadable-array-destructuring": 0,
    "unicorn/no-unreadable-iife": 2,
    "unicorn/no-unused-properties": 2,
    "unicorn/no-useless-error-capture-stack-trace": 2,
    "unicorn/no-useless-fallback-in-spread": 2,
    "unicorn/no-useless-length-check": 2,
    "unicorn/no-useless-promise-resolve-reject": 2,
    "unicorn/no-useless-spread": 2,
    "unicorn/no-useless-switch-case": 0,
    "unicorn/no-useless-undefined": 0,
    "unicorn/no-zero-fractions": 2,
    "unicorn/number-literal-case": 2,
    "unicorn/numeric-separators-style": [
      2,
      {
        number: {
          groupLength: 3,
          minimumDigits: 0,
        },
      },
    ],
    "unicorn/prefer-add-event-listener": 0,
    "unicorn/prefer-array-find": 2,
    "unicorn/prefer-array-flat": 2,
    "unicorn/prefer-array-flat-map": 2,
    "unicorn/prefer-array-index-of": 2,
    "unicorn/prefer-array-some": 2,
    "unicorn/prefer-at": 0,
    "unicorn/prefer-blob-reading-methods": 2,
    "unicorn/prefer-class-fields": 2,
    "unicorn/prefer-code-point": 2,
    "unicorn/prefer-date-now": 2,
    "unicorn/prefer-default-parameters": 2,
    "unicorn/prefer-export-from": 2,
    "unicorn/prefer-import-meta-properties": 2,
    "unicorn/prefer-includes": 2,
    "unicorn/prefer-json-parse-buffer": 2,
    "unicorn/prefer-math-trunc": 2,
    "unicorn/prefer-modern-math-apis": 2,
    "unicorn/prefer-native-coercion-functions": 2,
    "unicorn/prefer-negative-index": 0,
    "unicorn/prefer-number-properties": 2,
    "unicorn/prefer-object-from-entries": 2,
    "unicorn/prefer-optional-catch-binding": 2,
    "unicorn/prefer-prototype-methods": 0,
    "unicorn/prefer-query-selector": 2,
    "unicorn/prefer-reflect-apply": 2,
    "unicorn/prefer-regexp-test": 2,
    "unicorn/prefer-set-has": 0,
    "unicorn/prefer-single-call": 0,
    "unicorn/prefer-spread": 0,
    "unicorn/prefer-string-replace-all": 2,
    "unicorn/prefer-string-slice": 2,
    "unicorn/prefer-string-starts-ends-with": 2,
    "unicorn/prefer-string-trim-start-end": 2,
    "unicorn/prefer-switch": 0,
    "unicorn/prefer-ternary": 0,
    "unicorn/prefer-top-level-await": 0,
    "unicorn/prefer-type-error": 2,
    "unicorn/prevent-abbreviations": [
      2,
      {
        checkProperties: false,
        replacements: {
          args: false,
          pkg: false,
          props: false,
          ref: false,
          rel: false,
        },
      },
    ],
    "unicorn/relative-url-style": [2, "never"],
    "unicorn/require-array-join-separator": 2,
    "unicorn/require-module-specifiers": 2,
    "unicorn/require-number-to-fixed-digits-argument": 2,
    "unicorn/require-post-message-target-origin": 2,
    "unicorn/string-content": 0,
    "unicorn/template-indent": 2,
    "unicorn/text-encoding-identifier-case": 2,
    "unicorn/throw-new-error": 2,
    "vars-on-top": 2,
    yoda: [2, "never"],
  },
  settings: {
    "import/extensions": [".js", ".jsx", ".ts", ".ts", ".tsx"],
  },
});
